version = 1

# Tool-generated or configuration files.
[[annotations]]
path = [
  ".editorconfig",
  ".golangci.yml",
  ".gitignore",
  ".licensed.yml",
  ".licenses/**",
  "go.mod",
  "go.sum",
]
SPDX-FileCopyrightText = "Arduino s.r.l. and/or its affiliated companies"
SPDX-License-Identifier = "GPL-3.0-or-later"
